language: cpp

os:
  - linux
  - osx

osx_image: xcode9.3
dist: xenial

env:
  - lt_branch=master gui=true webui=1
  - lt_branch=RC_1_2 gui=true webui=1
  - lt_branch=master gui=false webui=1
  - lt_branch=master gui=false webui=0

matrix:
  exclude:
    - os: osx
      env: lt_branch=RC_1_1 gui=1 webui=1 # does not build due to the absent auto_ptr in xcode >= 9.3

notifications:
  email:
    on_success: change
    on_failure: change

cache:
  ccache: true
  directories:
    - $HOME/travis/deb
    - $HOME/travis/brew
# memory > 4 GiB is required for libtorrent build, GCC crashes otherwise
sudo: required

addons:
  coverity_scan:
    project:
      name: "qbittorrent/qBittorrent"
      description: "Build submitted via Travis CI"
    build_command_prepend: "./bootstrap.sh && ./configure $qmake_conf"
    build_command: "make -j2"
    branch_pattern: $coverity_branch
    notification_email: sledgehammer999@qbittorrent.org
  apt:
    sources:
      # sources list: https://github.com/travis-ci/apt-source-safelist/blob/master/ubuntu.json
      - sourceline: 'ppa:qbittorrent-team/qbittorrent-stable'
      - sourceline: 'ppa:beineri/opt-qt59-xenial'
      - sourceline: 'ppa:dluxen/cmake-backports'
      - sourceline: 'ppa:rakhimov/boost'
    packages:
      # packages list: https://github.com/travis-ci/apt-package-safelist/blob/master/ubuntu-trusty
      - [autoconf, automake, colormake]
      - [libboost-dev, libboost-system-dev]
      - libssl-dev
      - libtorrent-rasterbar-dev
      - [qt59base, qt59svg, qt59tools]
      - zlib1g-dev
      # required for Qt 5.9 from 'beineri' PPA
      - libgl1-mesa-dev

before_install:
  # only allow specific build for coverity scan, others will stop
  - if [ "$TRAVIS_BRANCH" = "$coverity_branch" ] && ! [ "$TRAVIS_OS_NAME" = "linux" -a "$libt_branch" = "RC_1_2" -a "$gui" = "true" -a "$build_system" = "qmake" ]; then exit ; fi

  - shopt -s expand_aliases
  - alias make="colormake -j2" # Using nprocs/2 sometimes may fail (gcc is killed by system)
  - qbt_path="$HOME/qbt_install"
  - cmake_conf="$cmake_conf -DCMAKE_INSTALL_PREFIX=$qbt_path"

  # options for specific branches
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      # setup virtual display for after_success target

      if [ "$gui" = "true" ]; then export "DISPLAY=:99.0" && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 ; fi ;

      # Qt 5.9
      PATH=/opt/qt59/bin:${PATH}
      # There is an outdated cmake in /usr/local/cmake-<version> which we don't want to use
      # but /usr/local/cmake-<version>/bin is in $PATH, therefore
      # remove all paths containing 'cmake' to use the executable from /usr/bin
      export PATH=`echo ${PATH} | awk -v RS=: -v ORS=: '/cmake/ {next} {print}'`
      qmake_conf="$qmake_conf PKG_CONFIG_PATH=/opt/qt59/lib/pkgconfig:$PKG_CONFIG_PATH"
      cmake_conf="$cmake_conf PKG_CONFIG_PATH=/opt/qt59/lib/pkgconfig:$PKG_CONFIG_PATH"
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      CXXFLAGS="$CXXFLAGS -Wno-unused-local-typedefs"

      openssl_root_path="/usr/local/opt/openssl"
      qmake_conf="$qmake_conf PKG_CONFIG_PATH=$openssl_root_path/lib/pkgconfig:$PKG_CONFIG_PATH"
      cmake_conf="$cmake_conf -DOPENSSL_ROOT_DIR=$openssl_root_path"
    fi
  - |
    if [ "$gui" = "false" ]; then
      cmake_conf="$cmake_conf -DCMAKE_DISABLE_FIND_PACKAGE_Qt5Widgets=ON"
    fi

  # print settings
  - echo $libt_branch
  - echo $gui
  - echo $ltconf
  - echo $cmake_conf

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      # dependencies
      brew update > /dev/null
      brew install ccache colormake boost openssl qt zlib
      brew link --force qt zlib
      PATH="/usr/local/opt/ccache/libexec:$PATH"

      if [ "$lt_branch" = "RC_1_1" ]; then
        brew install libtorrent-rasterbar
      else
        brew install boost openssl
      fi

      brew outdated cmake || brew upgrade cmake
      brew install ninja

      sudo ln -s /usr/local/opt/qt/mkspecs /usr/local/mkspecs
      sudo ln -s /usr/local/opt/qt/plugins /usr/local/plugins

      MY_CMAKE_OPENSSL_HINT="-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/"
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$lt_branch" = "master" ]; then
        cd "$TRAVIS_BUILD_DIR"
        mkdir libtorrent
        pushd libtorrent
        git clone --depth 1 --branch ${lt_branch} https://github.com/arvidn/libtorrent.git .
        mkdir -p cbuild/debug
        pushd cbuild/debug
        cmake -DCMAKE_BUILD_TYPE=Debug -Ddeprecated-functions=OFF "${MY_CMAKE_OPENSSL_HINT}" -G Ninja ../..
        cmake --build . && sudo cmake --build . --target install
        popd
        popd
    fi
  - |
    if [ "$TRAVIS_BRANCH" != "$coverity_branch" ]; then
      export use_ccache=true
      ccache -V && ccache --show-stats && ccache --zero-stats
    fi

script:
  - if [ "$TRAVIS_BRANCH" = "$coverity_branch" ]; then exit ; fi # skip usual build when running coverity scan
  - |
    cd "$TRAVIS_BUILD_DIR"
    mkdir build
    cd build
    cmake $cmake_conf -DWEBUI=$webui "$MY_CMAKE_OPENSSL_HINT" \
        -G "Ninja" -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE  ..
  - cmake --build . && cmake --build . --target install

after_success:
  - if [ "$gui" = 1 ]; then qbt_exe="qbittorrent" ; else qbt_exe="qbittorrent-nox" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd "$qbt_path/bin" ; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cd "$qbt_path/$qbt_exe.app/Contents/MacOS"
    fi
  - ./$qbt_exe --version

after_script:
  - if [ "$use_ccache" = true ]; then ccache --show-stats ; fi
